kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  # namespace: expense
  labels:
    app: nginx
    purpose: helm
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
      purpose: helm
  template:
    metadata:
      labels:
        app: nginx
        purpose: helm
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
---