apiVersion: v1
kind: Service
metadata:
  name: nginx
  # namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: nginx
    purpose: helm
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: {{ .Values.configmap.port }} #target-port
    nodePort: {{ .Values.service.nodePort }}