kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  labels:
    project: expense
    component: frontend
    tier: webtier
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: expense
      component: frontend
      tier: webtier
  template:
    metadata:
      labels:
        project: expense
        component: frontend
        tier: webtier
    spec:
      containers:
      - name: frontend
        image: msaivenkatasiva/expense-frontend:{{ .Values.deployment.imageVersion}}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subpath: nginx.conf
          readonly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend
          items:
          - key: nginx.conf
            path: nginx.conf