kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: 
    project: expense
    component: frontend
    tier: webtier
  ports:
  - protocol: TCP
    port: 80
    targetport: {{ .Values.configmap.port }}